In [38]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler, SMOTE

import seaborn as sns

In [39]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes(as_frame=True)
df = diabetes.frame

In [40]:
df.shape

(442, 11)

In [41]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [42]:
df.tail()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [43]:
df.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

In [46]:
# Target distribution

print("Outcome Distribution:")
print(df['target'].value_counts())

Outcome Distribution:
target
200.0    6
72.0     6
178.0    5
71.0     5
90.0     5
        ..
146.0    1
212.0    1
120.0    1
183.0    1
57.0     1
Name: count, Length: 214, dtype: int64

In [48]:
df.target

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [47]:
print("OUTCOME PERCENTAGE:")
print(df['target'].value_counts(normalize = True))

OUTCOME PERCENTAGE:
target
200.0    0.013575
72.0     0.013575
178.0    0.011312
71.0     0.011312
90.0     0.011312
           ...
146.0    0.002262
212.0    0.002262
120.0    0.002262
183.0    0.002262
57.0     0.002262
Name: proportion, Length: 214, dtype: float64

In [49]:
# Train test Split
X = df.drop(columns=['target'])
Y = df['target']

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [53]:
rus = RandomUnderSampler(random_state=42)

In [55]:
X_train_rus, y_train_rus = rus.fit_resample(X_train, y_train)

In [56]:
print("RUS")
print(y_train_rus.value_counts())

RUS
target
25.0     1
31.0     1
39.0     1
40.0     1
42.0     1
        ..
321.0    1
332.0    1
336.0    1
341.0    1
346.0    1
Name: count, Length: 199, dtype: int64

In [57]:
ros = RandomOverSampler(random_state=42)

In [58]:
X_train_ros, y_train_ros = ros.fit_resample(X_train, y_train)

In [59]:
print("ROS")
print(y_train_ros.value_counts())

ROS
target
144.0    5
150.0    5
280.0    5
125.0    5
59.0     5
        ..
134.0    5
244.0    5
57.0     5
148.0    5
302.0    5
Name: count, Length: 199, dtype: int64