In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", None)

In [10]:
df = sns.load_dataset('titanic')

In [14]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

Shape: (891, 15)
Columns: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
# Drop rows with missing target
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [19]:
target = "survived"

missing_target_count = df[target].isna().sum()
print("Rows with missing target:",missing_target_count)

Rows with missing target: 0

In [21]:
# drop the rows has the missing target
df = df.dropna(subset = [target])
print("after dropping:",missing_target_count)

after dropping: 0

In [28]:
# seperate X (FEATURES) and Y (TARGET)
X = df.drop(columns=[target])
y = df[target]
print(X.shape)
print(df.shape)
print(y.shape)

(891, 14)
(891, 15)
(891,)

In [29]:
print("Target distribution on full data:")
print(y.value_counts())

Target distribution on full data:
survived
0    549
1    342
Name: count, dtype: int64

In [33]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42, stratify=y)

In [36]:
print("Shape X_TRAIN:", X_train.shape)
print("Shape X_TEST:", X_test.shape)
print("Shape y_TRAIN:", y_train.shape)
print("Shape y_TEST:", y_test.shape)

Shape X_TRAIN: (712, 14)
Shape X_TEST: (179, 14)
Shape y_TRAIN: (712,)
Shape y_TEST: (179,)